fix building process
encountered issue:

ERROR: unable to select packages:
  nginx-mod-http-headers-more-1.22.1-r1:
    breaks: world[nginx-mod-http-headers-more=1.22.1-r0]